### ISSUE TITLE
how to attach to the OpenSimulator console after first install?

### ISSUE THREAD

**Issue by giodegas** [QuantumObject/docker-opensimulator#4]
Hi again.
After the first run, I always restart the container with

    docker restart <container name>

then

    docker exec -it <container name> /bin/bash

I can see the OpenSim messages on /var/log, but how do I then regain access to the OpenSim.exe console?
For example I have to create new avatar accounts... 
Or maybe the container (or its derivaritve) should also include also a web interface to OpenSim like [WiFi](http://opensimulator.org/wiki/Wifi) ?

**Comment by angelrr7702** [comment]
Hi,
 
 After 
 
       docker exec -it <container name> /bin/bash 

 You need to run command : 

       export TERM=xterm

This to make sure you can use some bash program like top and nano .

if you check with top you be able to see that opensim-ode.sh is running .. In my container at  the moment I use runit like init system ..(in the future maybe move to systemd) 

opensim is the service that make it work in the background ... at /etc/service you be able to see it ..
 
to stop it you need : 

   sv stop opensim

and to start again 

   sv start opensim

how to access the console .. I need to check .. still no sure ..  Opensim run a scrit at /etc/service/opensim/run that exec the opensim-ode.sh ... the after_install scritp at /sbin/after_install execute that scrip to create intitial configuration and create the run script by changing name of file unrun to run at /etc/service/opensim/ but it delete itself at the end ,,,

 I try to stop opensim (sv stop opensim)  and try to run opensim-ode.sh but that fail ... because port in used ...appear that run script missing the finish script to stop mono too... opensim-ode.sh execute it . but stoping opensim-ode.sh don't stop all the other process that mono running ...

 sorry unable to give a clear response but I will continue researching and I will update when I found a solutions to it ..


sincerely
Angel Rodriguez

**Comment by giodegas** [comment]
ok, thank you. 
Maybe opensim-ode.sh should be launched in a [screen](http://www.rackaid.com/blog/linux-screen-tutorial-and-how-to) session?

    screen -d -m sh opensimode.sh

to later it could be possible later to attach to the opensim console.

**Comment by angelrr7702** [comment]
I connected to console on this way : 
         docker exec -it <container name> /bin/bash 
         export TERM=xterm
         mv /etc/service/opensim/run /etc/service/opensim/unrun
         exit
         docker stop <container name>
         docker start <container name>
         docker exec -it <container name> /bin/bash 
         export TERM=xterm
         cd /opt/opensim-0.8.1/bin/
         mono ./OpenSim.exe

when done using the console need to quit to exit and them 

           mv /etc/service/opensim/unrun /etc/service/opensim/run
         
note : I update the container from 0.8.1-rc2 to 0.8.1  for that reason 'cd /opt/opensim-0.8.1/bin/'
I will try to include WiFi for that reason at the moment I will no try to add another way to run console or used screen . 

sincerely
Angel Rodriguez

**Comment by giodegas** [comment]
very nice, it is enough for now, thank you.
To use work without xterm, I found useful:

    export TERM=vt100
